-- CreateTable
CREATE TABLE "CONTROLE_UPLOAD" (
    "ID_ARQUIVO" TEXT NOT NULL,
    "STATUS" BOOLEAN NOT NULL,
    "EVENTO" TEXT NOT NULL,
    "VALORES" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CONTROLE_UPLOAD_pkey" PRIMARY KEY ("ID_ARQUIVO")
);

-- CreateTable
CREATE TABLE "DATA_UPLOAD" (
    "ID_DATA" TEXT NOT NULL,
    "NOME" TEXT NOT NULL,
    "VALOR" TEXT NOT NULL,

    CONSTRAINT "DATA_UPLOAD_pkey" PRIMARY KEY ("ID_DATA")
);

-- CreateTable
CREATE TABLE "_SheetCells" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "_SheetCells_AB_unique" ON "_SheetCells"("A", "B");

-- CreateIndex
CREATE INDEX "_SheetCells_B_index" ON "_SheetCells"("B");

-- AddForeignKey
ALTER TABLE "_SheetCells" ADD CONSTRAINT "_SheetCells_A_fkey" FOREIGN KEY ("A") REFERENCES "DATA_UPLOAD"("ID_DATA") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_SheetCells" ADD CONSTRAINT "_SheetCells_B_fkey" FOREIGN KEY ("B") REFERENCES "CONTROLE_UPLOAD"("ID_ARQUIVO") ON DELETE CASCADE ON UPDATE CASCADE;
