-- CreateTable
CREATE TABLE "CAD_UF" (
    "ID_UF" TEXT NOT NULL,
    "UF" TEXT NOT NULL,

    CONSTRAINT "CAD_UF_pkey" PRIMARY KEY ("ID_UF")
);

-- CreateTable
CREATE TABLE "CAD_CIDADE" (
    "ID_CIDADE" TEXT NOT NULL,
    "CIDADE" TEXT NOT NULL,
    "ID_UF" TEXT NOT NULL,

    CONSTRAINT "CAD_CIDADE_pkey" PRIMARY KEY ("ID_CIDADE")
);

-- CreateTable
CREATE TABLE "CAD_CURSO" (
    "ID_CURSO" TEXT NOT NULL,
    "DESC_CURSO" TEXT NOT NULL,
    "QTD_AULAS" INTEGER NOT NULL,
    "DURACAO_MEDIA" DECIMAL(65,30) NOT NULL,

    CONSTRAINT "CAD_CURSO_pkey" PRIMARY KEY ("ID_CURSO")
);

-- CreateTable
CREATE TABLE "ASSOC_TRABALHADOR_CURSO" (
    "CPF" TEXT NOT NULL,
    "DATA_INSCRICAO" TIMESTAMP(3) NOT NULL,
    "DATA_CONCLUSAO" TIMESTAMP(3) NOT NULL,
    "ID_CURSO" TEXT NOT NULL,
    "ID_CIDADE" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "CAD_USUARIO" (
    "ID_USUARIO" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "DDCELULARSMS" TEXT NOT NULL,
    "CODIGO" TEXT NOT NULL,
    "DATA_CONSENTIMENTO_LGPD" TIMESTAMP(3) NOT NULL,
    "ID_ORGANIZACAO" TEXT NOT NULL,

    CONSTRAINT "CAD_USUARIO_pkey" PRIMARY KEY ("ID_USUARIO")
);

-- CreateTable
CREATE TABLE "CAD_ORGANIZACAO" (
    "ID_ORGANIZACAO" TEXT NOT NULL,
    "DESC_ORGANIZACAO" TEXT NOT NULL,
    "TIPO" TEXT NOT NULL,

    CONSTRAINT "CAD_ORGANIZACAO_pkey" PRIMARY KEY ("ID_ORGANIZACAO")
);

-- CreateTable
CREATE TABLE "CAD_INDICADOR" (
    "ID_INDICADOR" TEXT NOT NULL,
    "DESC_INDICADOR" TEXT NOT NULL,
    "ID_ORGANIZACAO" TEXT NOT NULL,

    CONSTRAINT "CAD_INDICADOR_pkey" PRIMARY KEY ("ID_INDICADOR")
);

-- CreateTable
CREATE TABLE "ASSOC_INDICADOR_CURSO" (
    "ID_INDICADOR" TEXT NOT NULL,
    "ID_CURSO" TEXT NOT NULL,

    CONSTRAINT "ASSOC_INDICADOR_CURSO_pkey" PRIMARY KEY ("ID_INDICADOR","ID_CURSO")
);

-- CreateTable
CREATE TABLE "ASSOC_TRABALHADOR_PRODUTOR" (
    "CPF" TEXT NOT NULL,
    "DATA_INICIO" TIMESTAMP(3) NOT NULL,
    "DATA_FIM" TIMESTAMP(3) NOT NULL,
    "ID_PRODUTOR" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "CAD_PRODUTOR" (
    "ID_PRODUTOR" TEXT NOT NULL,
    "DESC_PRODUTOR" TEXT NOT NULL,
    "ID_ORGANIZACAO" TEXT NOT NULL,
    "ID_CIDADE" TEXT NOT NULL,

    CONSTRAINT "CAD_PRODUTOR_pkey" PRIMARY KEY ("ID_PRODUTOR")
);

-- CreateTable
CREATE TABLE "CAD_INDICADOR_META" (
    "ID_META" TEXT NOT NULL,
    "ANO_META" TIMESTAMP(3) NOT NULL,
    "META" TEXT NOT NULL,
    "PERCENTUAL_REALIZADO" DECIMAL(65,30) NOT NULL,
    "producerId" TEXT NOT NULL,
    "indicatorId" TEXT NOT NULL,

    CONSTRAINT "CAD_INDICADOR_META_pkey" PRIMARY KEY ("ID_META")
);

-- CreateTable
CREATE TABLE "SUM_VALOR_INDICADOR" (
    "ID_VALOR_INDICADOR" TEXT NOT NULL,
    "VALOR_INDICADO" DECIMAL(65,30) NOT NULL,
    "AGRUPADOR_SUMARIZACAO" TEXT NOT NULL,
    "producer_id" TEXT NOT NULL,
    "indicator_id" TEXT NOT NULL,

    CONSTRAINT "SUM_VALOR_INDICADOR_pkey" PRIMARY KEY ("ID_VALOR_INDICADOR")
);

-- CreateIndex
CREATE UNIQUE INDEX "CAD_UF_UF_key" ON "CAD_UF"("UF");

-- CreateIndex
CREATE UNIQUE INDEX "ASSOC_TRABALHADOR_CURSO_CPF_key" ON "ASSOC_TRABALHADOR_CURSO"("CPF");

-- CreateIndex
CREATE UNIQUE INDEX "ASSOC_TRABALHADOR_PRODUTOR_CPF_key" ON "ASSOC_TRABALHADOR_PRODUTOR"("CPF");

-- AddForeignKey
ALTER TABLE "CAD_CIDADE" ADD CONSTRAINT "CAD_CIDADE_ID_UF_fkey" FOREIGN KEY ("ID_UF") REFERENCES "CAD_UF"("ID_UF") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ASSOC_TRABALHADOR_CURSO" ADD CONSTRAINT "ASSOC_TRABALHADOR_CURSO_ID_CURSO_fkey" FOREIGN KEY ("ID_CURSO") REFERENCES "CAD_CURSO"("ID_CURSO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ASSOC_TRABALHADOR_CURSO" ADD CONSTRAINT "ASSOC_TRABALHADOR_CURSO_ID_CIDADE_fkey" FOREIGN KEY ("ID_CIDADE") REFERENCES "CAD_CIDADE"("ID_CIDADE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CAD_USUARIO" ADD CONSTRAINT "CAD_USUARIO_ID_ORGANIZACAO_fkey" FOREIGN KEY ("ID_ORGANIZACAO") REFERENCES "CAD_ORGANIZACAO"("ID_ORGANIZACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CAD_INDICADOR" ADD CONSTRAINT "CAD_INDICADOR_ID_ORGANIZACAO_fkey" FOREIGN KEY ("ID_ORGANIZACAO") REFERENCES "CAD_ORGANIZACAO"("ID_ORGANIZACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ASSOC_INDICADOR_CURSO" ADD CONSTRAINT "ASSOC_INDICADOR_CURSO_ID_INDICADOR_fkey" FOREIGN KEY ("ID_INDICADOR") REFERENCES "CAD_INDICADOR"("ID_INDICADOR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ASSOC_INDICADOR_CURSO" ADD CONSTRAINT "ASSOC_INDICADOR_CURSO_ID_CURSO_fkey" FOREIGN KEY ("ID_CURSO") REFERENCES "CAD_CURSO"("ID_CURSO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ASSOC_TRABALHADOR_PRODUTOR" ADD CONSTRAINT "ASSOC_TRABALHADOR_PRODUTOR_ID_PRODUTOR_fkey" FOREIGN KEY ("ID_PRODUTOR") REFERENCES "CAD_PRODUTOR"("ID_PRODUTOR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CAD_PRODUTOR" ADD CONSTRAINT "CAD_PRODUTOR_ID_ORGANIZACAO_fkey" FOREIGN KEY ("ID_ORGANIZACAO") REFERENCES "CAD_ORGANIZACAO"("ID_ORGANIZACAO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CAD_PRODUTOR" ADD CONSTRAINT "CAD_PRODUTOR_ID_CIDADE_fkey" FOREIGN KEY ("ID_CIDADE") REFERENCES "CAD_CIDADE"("ID_CIDADE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CAD_INDICADOR_META" ADD CONSTRAINT "CAD_INDICADOR_META_producerId_fkey" FOREIGN KEY ("producerId") REFERENCES "CAD_PRODUTOR"("ID_PRODUTOR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CAD_INDICADOR_META" ADD CONSTRAINT "CAD_INDICADOR_META_indicatorId_fkey" FOREIGN KEY ("indicatorId") REFERENCES "CAD_INDICADOR"("ID_INDICADOR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SUM_VALOR_INDICADOR" ADD CONSTRAINT "SUM_VALOR_INDICADOR_producer_id_fkey" FOREIGN KEY ("producer_id") REFERENCES "CAD_PRODUTOR"("ID_PRODUTOR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SUM_VALOR_INDICADOR" ADD CONSTRAINT "SUM_VALOR_INDICADOR_indicator_id_fkey" FOREIGN KEY ("indicator_id") REFERENCES "CAD_INDICADOR"("ID_INDICADOR") ON DELETE RESTRICT ON UPDATE CASCADE;
