-- CreateTable
CREATE TABLE "SESSOES" (
    "ID_SESSAO" SERIAL NOT NULL,
    "TOKEN" TEXT NOT NULL,
    "SESSAO_VALIDA" BOOLEAN NOT NULL DEFAULT true,
    "DATA_ATUALIZACAO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USUARIO" TEXT NOT NULL,

    CONSTRAINT "SESSOES_pkey" PRIMARY KEY ("ID_SESSAO")
);

-- AddForeignKey
ALTER TABLE "SESSOES" ADD CONSTRAINT "SESSOES_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "CAD_USUARIO"("ID_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;
