-- CreateTable
CREATE TABLE "CAD_CANAL_LEADS" (
    "ID_CANAL" TEXT NOT NULL,
    "DESC_CANAL" TEXT NOT NULL,

    CONSTRAINT "CAD_CANAL_LEADS_pkey" PRIMARY KEY ("ID_CANAL")
);

-- CreateIndex
CREATE UNIQUE INDEX "CAD_CANAL_LEADS_DESC_CANAL_key" ON "CAD_CANAL_LEADS"("DESC_CANAL");