UPDATE "CAD_USUARIO" 
SET "ID_ORGANIZACAO" = (SELECT "ID_ORGANIZACAO" FROM "CAD_ORGANIZACAO" 	WHERE "CODIGO_ORGANIZACAO" = 'ORG1')
WHERE "EMAIL" = 'teste@cpqd.com.br';

UPDATE "CAD_USUARIO" 
SET "ID_ORGANIZACAO" = (
	SELECT "ID_ORGANIZACAO" 
	FROM "CAD_ORGANIZACAO" 
	WHERE "CODIGO_ORGANIZACAO" = 'ORG2'
)
WHERE "EMAIL" = 'mauricio@jaentendi.com.br';

UPDATE "CAD_USUARIO" 
SET "ID_ORGANIZACAO" = (
	SELECT "ID_ORGANIZACAO" 
	FROM "CAD_ORGANIZACAO" 
	WHERE "CODIGO_ORGANIZACAO" = 'ORG3'
)
WHERE "EMAIL" = 'rogerio@jaentendiagro.com.br';